### ISSUE TITLE
Running example  with aarch64 fails

### ISSUE THREAD

**Issue by sigmaSd** [AldaronLau/smelling_salts#8]
**Describe the bug**
Running example  with aarch64 fails

**To Reproduce**
1. cargo r --example readme  --target aarch64-linux-android
2. the linker used is "/opt/android-ndk/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android23-clang"

**Error:**
```
  = note: ld.lld: error: undefined symbol: __errno_location
          >>> referenced by linux.rs:68 (src/ffi/linux.rs:68)
          >>> smelling_salts-bd67eb5ffa7ff221.477cayjzrv96mki7.rcgu.o:(smelling_salts::ffi::error::hc10de5e20f7804df) in archive /home/mrcool/dev/rust/cargo_target_dir_aarch64/aarch64-linux-android/debug/deps/libsmelling_salts-bd67eb5ffa7ff221.rlib
          clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by sigmaSd** [comment]
Stabbing that line makes it compile.

Using wavy on android via https://termux.com/ :

1- microphone panics here  https://github.com/libcala/wavy/blob/main/src/ffi/linux/microphone.rs#L78

2- speakers panic here https://github.com/libcala/wavy/blob/main/src/ffi/linux/speakers.rs#L87

Also with the speakers usage I get a warning `WARNING: linker: unsupported flags DT_FLAGS_1=0x8000001`

**Comment by AldaronLau** [comment]
@sigmaSd Thanks, looks like the errno symbol is defined differently depending on the libc version (and Android uses a different libc).

**Comment by AldaronLau** [comment]
@sigmaSd The new version (0.2.3) of smelling_salts should compile for Android, I think the problem from you second issue should be opened on wavy, unless it triggers in the smelling_salts readme example as well, so I'm closing this now.  Re-open if I'm wrong.
